### ISSUE TITLE
OpenLogin installation via script

### ISSUE THREAD

**Issue by ungarson** [MetaMask/torus-documentation#53]
When I use script tag specified in the [installation page](https://docs.tor.us/open-login/api-reference/installation), I end up with the error that Buffer is not defined
`<script src="https://cdn.jsdelivr.net/npm/@toruslabs/openlogin@0"></script>`

But this one works fine:
`<script src="https://cdn.jsdelivr.net/npm/@toruslabs/openlogin"></script>`

I have Google Chrome Version 90.0.4430.93 (Official Build) (x86_64), macos latest version

**Comment by himanshuchawla009** [comment]
Hi, could you attach screenshot of complete error log. @ungarson

**Comment by ungarson** [comment]
Closed, since it's outdated
