### ISSUE TITLE
link for comprehensive list is not valid

### ISSUE THREAD

**Issue by gnujoow** [MetaMask/torus-documentation#74]
https://github.com/torusresearch/torus-documentation/blame/a11cda5d0bf92adecc36b2b0acad48080511a851/docs/customauth/what-is-customauth.mdx#L9

https://docs.tor.us/customauth/verifiers/supported-logins is not exist

caused by https://github.com/torusresearch/torus-documentation/pull/63

**Comment by gnujoow** [comment]
cc: @kanishkatn

**Comment by kanishkatn** [comment]
Thank you for reporting the issue. 

Here's the link you're looking for: https://docs.tor.us/customauth/verifiers
